### ISSUE TITLE
Source connector `streaming` from server stops processing records after 6 hours

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/http-source-connector#148]
Run the connector for several hours, and it will eventually stop. As this is TCP, I would not expect errors.

Connector configuration file:

```yaml
apiVersion: 0.1.0
meta:
  version: 0.3.1
  name: car-callout
  type: http-source
  topic: cars 
http:
  endpoint: https://demo-data.infinyon.com/api/car-stream
  method: GET
  stream: true
  delimiter: "\n\n"
```

Error in the log:

```
2024-01-31T10:25:09.753239Z ERROR http_source::http_streaming_source: could not read data from http response stream: request or response body error: error reading a body from connection: unexpected EOF during chunk size line
```

Connector status after failure:

```
% cdk deploy list
 NAME         STATUS  
 car-callout  Stopped
```
