### ISSUE TITLE
Reference secret name in http header

### ISSUE THREAD

**Issue by digikata** [infinyon/http-source-connector#25]
A common use of http headers is to insert authorization tokens, a header should be able to reference a secret by name. There are several ways to accomplish this which need further analysis:
- full header lines as secret names for the http connector
- split header name, value config, and allow value to reference secret names
- provide a sdk method for config parsing substrings of some config items for secret replacement
- others?

Needs PRD for further spec and options, but one desire by @aj is to keep some resemblance to curl syntax.

**Comment by sehz** [comment]
In the http header case, we probably interpolate values like this:

```
http:
  endpoint: "https://github.com/myrepo"
  interval: 10s
  headers:
       - key: Authorization
          value: "token ${{   secret.my_key }}"
```

Interpolation syntax should be similar to what are going to use in the materialize view as well. 
There are many existing interpolation syntax we can borrow;

https://www.koding.com/docs/terraform/configuration/interpolation.html/
https://docs.github.com/en/actions/learn-github-actions/expressions.
etc

**Comment by digikata** [comment]
Another way is to put the entire value or header pair in the secret:
```
http:
  endpoint: "https://github.com/myrepo"
  interval: 10s
  headers:
       - key: Authorization
         value:
            secret:
               name: AUTH_TOKEN
 ```
where: `fluvio cloud secret set -c AUTH_TOKEN "token long-auth-str"`

or 

```
http:
  endpoint: "https://github.com/myrepo"
  interval: 10s
  headers:
       - secret:
            name: HEADER_AUTH
 ```
where: `fluvio cloud secret set -c HEADER_AUTH "Authorization: token long-auth-str"`
