### ISSUE TITLE
improve syntax parsing and logging

### ISSUE THREAD

**Issue by digikata** [infinyon/http-source-connector#275]
e.g. config with subscription messages indented at the wrong level is accepted and no subscription messages for websocket are sent

bad config:
```
meta:
  version: latest
  name: websocket-messages-connector
  type: websocket-source
  topic: TOPIC
  create_topic: false
  producer:
    linger: 0ms
http:
  endpoint: ws://127.0.0.1:8080/websocket-echo
  subscription_messages:
    - 'hello 1'
    - 'hello 2'
    - 'hello 3'
```

good config:
```
meta:
  version: latest
  name: websocket-messages-connector
  type: websocket-source
  topic: TOPIC
  create_topic: false
  producer:
    linger: 0ms
http:
  endpoint: ws://127.0.0.1:8080/websocket-echo
  websocket_config:
    subscription_messages:
      - 'hello 1'
```
